
// TODO: define 24-hour clock

[[terms]]
== Terms, definitions and abbreviations

=== Terms and Definitions

==== Basic concepts

[[term-time]]
===== time

mark attributed to an _instant_ (<<term-instant>>) by means of a specified time scale (<<term-time-scale>>)

[.source]
IEV 113-01-12, modified -- preferred term "`time`" placed prior to "`date`", replaced "`date`" with this preferred term "`time`" in Note 1, omission of Note 2, renumbering of Note 3 to Note 2, added Note 3 and Note 4 to entry

NOTE: On a time scale consisting of successive steps, two distinct instants may be expressed by the same time (see Note 1 of the term _time scale_ (<<term-time-scale>>)).

NOTE: In common language, the term "`date`" is mainly used when the time scale is a calendar as a sequence of days.

NOTE: In IEV 113-01-12 this definition corresponds with the term "`date`".

NOTE: The term "`time`" is often used in common language. However, it should only be used if the meaning is clearly visible from the context, since the term "`time`" is also used with other meanings.


[[term-instant]]
===== instant

point on the _time axis_ (<<term-time-axis>>)

[.source]
IEV 113-01-08

NOTE: An instantaneous event occurs at a specific instant.

[[term-time-axis]]
===== time axis

mathematical representation of the succession in time of instantaneous events along a unique axis

[.source]
IEV 113-01-07

NOTE: According to the special theory of relativity, the time axis depends on the choice of a spatial reference frame.

[[term-time-scale]]
===== time scale

system of ordered marks which can be attributed to _instants_ (<<term-instant>>) on the _time axis_ (<<term-time-axis>>), one instant being chosen as the origin

[.source]
IEV 113-01-11, modified -- references to terms defined in this document in Note 1 to entry replaced with references to their definitions in this document

NOTE: A time scale may amongst others be chosen as:
—	continuous, e.g. international atomic time (TAI) (see IEV 713-05-18);
—	continuous with discontinuities, e.g. _Coordinated Universal Time (UTC)_ (<<term-utc>>) due to leap sec-onds, standard time due to summer time and winter time;
—	successive steps, e.g. usual calendars, where the _time axis_ (<<term-time-axis>>) is split up into a succession of consecutive time intervals and the same mark is attributed to all instants of each time interval;
—	discrete, e.g. in digital techniques.

NOTE: For physical and technical applications, a time scale with quantitative marks is preferred, based on a chosen initial instant together with a unit of measurement.

NOTE: Customary time scales use various units of measurement in combination, such as second, minute, hour, or various time intervals of the calendar such as calendar day, calendar month and calendar year.

[[term-time-scale-unit]]
===== time scale unit

unit of measurement of a _time scale_ (<<term-time-scale>>)

[example]
calendar year, calendar month, calendar day are time scale units of the Gregorian calendar; clock hour, clock minutes, clock seconds are time scale units of the 24-hour time system clock.

[[term-clock]]
===== clock

_time scale_ (<<term-time-scale>>) suited for intraday time measurements that includes the _time scale units_ (<<term-time-scale-unit>>) of _clock second_ (<<term-clock-second>>), _clock minute_ (<<term-clock-minute>>) and _clock hour_ (<<term-clock-hour>>)

[example]
The 24-hour clock is a type of clock.

[[term-time-interval]]
===== time interval

part of the _time axis_ (<<term-time-axis>>) limited by two _instants_ (<<term-instant>>) and, unless otherwise stated, the limiting instants themselves.

[.source]
IEV 113-01-10, modified -- merged Note 1 to entry into definition, added reference to terms defined in this document, omission of Notes 2 and 3 for clarity of this document

[[term-recurring-time-interval]]
===== recurring time interval

series of consecutive _time intervals_ (<<term-time-interval>>) of the same _duration_ (<<term-duration>>) or nominal duration

NOTE: If the duration of the time intervals is measured in calendar entities, the duration of each time interval depends on the calendar dates of its start and its end.

NOTE: If the time interval is repeating a set of rules ISO 8601-2, Clause 5 "`Repeat Rules for Recurring Time Intervals`", applies.

[[term-duration]]
===== duration

non-negative quantity equal to the difference between the times of the final _instant_ (<<term-instant>>) and the initial instant of the _time interval_ (<<term-time-interval>>)

[.source]
IEV 113-01-13, modified -- reference to quantitative marks deleted; definition sourced from Note 1 of entry; updated references to the definitions within this document, deleted Note 1 to entry, adopted a modified Note 2 to entry and Note 3 to entry]

NOTE: The duration is one of the base quantities in the International System of Quantities (ISQ) on which the International System of Units (SI) is based. The term "`time`" instead of "`duration`" is often used in this context and also for an infinitesimal duration.

NOTE: For the term "`duration`", expressions such as "`time`" or "`time interval`" are often used, but the term "`time`" is not recommended in this sense and the term "`time interval`" is deprecated in this sense to avoid confusion with the concept of "`time interval`".

NOTE: The exact duration of a calendar year,  calendar month,  calendar week, calendar day, clock hour, or clock minute, depends on when they occur (for example a month can be 28, 29, 30, or 31 days, a minute can be 59, 60, or 61 seconds, etc). Therefore, exact duration can only be evaluated if the exact duration of the components are known.

[[term-utc]]
===== Coordinated Universal Time
alt:[UTC]

_time scale_ (<<term-time-scale>>) produced by the Bureau International des Poids et Mesures (BIPM) with the same rate as International Atomic Time (TAI), but differing from TAI only by an integral number of seconds

[.source]
BIPM Recommendation CCTF 3 (2017), including the definition of TAI as Note 1 to entry]

NOTE: TAI is a continuous time scale produced by the BIPM based on the best realizations of the SI second. TAI is a realization of Terrestrial Time (TT) with the same rate as that of TT, as defined by the International Astronomical Union Resolution B1.9 (2000).

NOTE: UTC is the time standard commonly used across the world from which local time is derived.

[[term-utc-of-day]]
===== UTC of day

_time of day_ (<<term-time-of-day>>) in _UTC_ (<<term-utc>>)

[[term-standard-time]]
===== standard time

_time scale_ (<<term-time-scale>>) derived from _UTC_ (<<term-utc>>), by a time shift established in a given location by the competent authority

[.source]
IEV 113-01-17, modified - Note 1 added to entry, added examples

[example]
Central European Time (CET), Central European Summer Time (CEST), Eastern Standard Time (EST), Pacific Standard Time (PST), China Standard Time (CST), Hong Kong Time (HKT), Japanese Standard Time (JST), etc.

NOTE: This time shift may be varied in the course of a year.

[[term-local-time-scale]]
===== local time scale

Locally-applicable _time scale_ (<<term-time-scale>>) such as _standard time_ (<<term-standard-time>>) or a non-_UTC_ (<<term-utc>>) based time scale

[[term-time-of-day]]
===== time of day

quantitative expression marking an _instant_ (<<term-instant>>) within a _calendar day_ (<<term-calendar-day>>) by the _duration_ (<<term-duration>>) elapsed after the beginning of the day

[.source]
IEV 113-01-18, modified -- "`time of day`" is the preferred term in this document, generalized to not require local standard time, Note 1 edited to remove examples originating from this document, Note 4 added]

NOTE: Usually, time of day is represented by the number of hours elapsed after beginning of day the number of minutes elapsed after the last full hour, and, if necessary, the number of seconds elapsed after the last full minute, possibly with decimal parts of a second.

NOTE: The duration used in the definition is modified for special situations (daylight saving time, leap second).

NOTE: In IEV 113-01-18 this definition corresponds closely with the term "`clock time`" with the exception that the time scale (3.4) is not defined here.

NOTE: The time scale used by a time of day may or may not be based on _UTC_ (<<term-utc>>).

[[term-local-time-of-day]]
===== local time of day

_time of day_ (<<term-time-of-day>>) in a _local time scale_ (<<term-local-time-scale>>)

[[term-calendar]]
===== calendar

_time scale_ (<<term-time-scale>>) that uses the _time scale unit_ (<<term-time-scale-unit>>) of _calendar day_ (<<term-calendar-day>>) as its basic unit

NOTE: _calendar month_ (<<term-calendar-month>>) and _calendar year_ (<<term-calendar-year>>) are time scale units often included in a calendar

[example]
The Gregorian calendar is a type of calendar.

[[term-gregorian-calendar]]
===== Gregorian calendar

_calendar_ (<<term-calendar>>) in general use, introduced in 1582, to define a calendar year (<<term-calendar-year>>) that more closely approximates the tropical year than the Julian calendar

NOTE: The term Gregorian calendar is used to refer to the time scale described in ISO 8601, 4.2.1.

[[term-common-year]]
===== common year

_calendar year_ (<<term-calendar-year>>) in the _Gregorian calendar_ (<<term-gregorian-calendar>>) that has 365 _calendar days_ (<<term-calendar-day>>)

[[term-leap-year]]
===== leap year

_calendar year_ (<<term-calendar-year>>) in the _Gregorian calendar_ (<<term-gregorian-calendar>>) that has 366 _calendar days_ (<<term-calendar-day>>)

[[term-centennial-year]]
===== centennial year

_calendar year_ (<<term-calendar-year>>) in the _Gregorian calendar_ (<<term-gregorian-calendar>>) whose year number is divisible without remainder by hundred

[[term-leap-second]]
===== leap second

intentional time step of one _second_ (<<term-second>>) to adjust _UTC_ (<<term-utc>>) to ensure appropriate agreement with UT1, a _time scale_ (<<term-time-scale>>) based on the rotation of the Earth

NOTE: See also ITU-R TF.460-6.

NOTE: An inserted second is called positive leap second and an omitted second is called negative leap second. A positive leap second is inserted after [23:59:59Z] and can be represented as [23:59:60Z]. A negative leap second is achieved by the omission of [23:59:59Z]. Insertion or omission takes place as determined by IERS, normally on 30 June or 31 December, but if necessary on 31 March or 30 September.


==== Time and Date Units

[[term-second]]
===== second

base unit of measurement of time in the International System of Units (SI) as defined by the International Committee of Weights and Measures (CIPM, i.e. Comité International des Poids et Mesures)

NOTE: See also ISO 80000-3.

NOTE: It is the base unit for expressing duration.


[[term-clock-second]]
===== clock second

_time interval_ <<term-time-interval>> whose duration is one _second_ (<<term-second>>), which in the 24-hour _clock_ (<<term-clock>>) is represented by a two-digit ordinal number from [00]  identifying the first second to [59] or [60] identifying the last second of a clock minute ([59] without a leap second,  [60] with a leap second)

NOTE: Clock second is in common parlance often referred to as second, however in this document clock second and second have different definitions.

[[term-minute]]
===== minute

unit of time, equal to 60 _seconds_ (<<term-second>>)

NOTE: See also ISO 80000-3.

NOTE: The duration of a minute is 60 seconds except if modified by the insertion or deletion of a leap second

[[term-clock-minute]]
===== clock minute

_time interval_ <<term-time-interval>> whose duration is one _minute_ (<<term-minute>>), which in the 24-hour clock is identified by a two-digit ordinal number from [00] identifying the first minute to [59] identifying the last minute of a clock hour

NOTE: Clock minute is in common parlance often referred to as minute, however in this document clock minute and minute have different definitions.

[[term-hour]]
===== hour

unit of time, equal to 60 _minutes_ (<<term-minute>>)

NOTE: See also ISO 80000-3.

[[term-clock-hour]]
===== clock hour

_time interval_ <<term-time-interval>> of duration one _hour_ (<<term-hour>>), which in the 24-hour clock system is identified by a two-digit ordinal number from [00] identifying the first hour through [23] identifying the last hour of a calendar day

NOTE: Clock hour is in common parlance often referred to as hour, however in this document clock hour and hour have different definitions.

[[term-date]]
===== date

a _calendar date_ (<<term-calendar-date>>), _ordinal date_ (<<term-ordinal-date>>), or _week date_ (<<term-week-date>>).

[[term-calendar-date]]
===== calendar date

a particular _calendar day_ (<<term-calendar-day>>) represented by its _calendar year_ (<<term-calendar-year>>), its _calendar month_ (<<term-calendar-month>>), and its ordinal number within its calendar month


[[term-ordinal-date]]
===== ordinal date

_date_ (<<term-date>>) representing a particular _calendar day_ (<<term-calendar-day>>) represented by its _calendar year_ (<<term-calendar-year>>) and its ordinal number within its calendar year

[[term-week-date]]
===== week date

a particular _calendar day_ (<<term-calendar-day>>) represented by the _calendar year_ (<<term-calendar-year>>) to which its _calendar week_ (<<term-calendar-year>>) belongs, the ordinal number of its calendar week within that calendar year, and its ordinal number within its _calendar week_ (<<term-calendar-week>>)

[[term-day]]
===== day

_duration_ (<<term-duration>>) of a _calendar day_ (<<term-calendar-day>>)

NOTE: The term "`day`" applies also to the duration of any _time interval_ (<<term-time-interval>>) which starts at a certain time of day on a certain calendar day and ends at the same time of day on the next calendar day.

NOTE: See also ISO 80000-3.

[[term-calendar-day]]
===== calendar day

_time interval_ <<term-time-interval>> starting at the beginning of the day and ending with the beginning of the next day (the latter being the starting instant of the next calendar day)

NOTE: Calendar day is in common parlance often referred to as day, however in this document calendar day and day have different definitions.

NOTE: The duration of a calendar day using the 24-hour clock is 24 hours; except if modified by:
— the insertion or deletion of leap seconds, by decision of the International Earth Rotation Service (IERS), or
— the insertion or deletion of other time intervals, as may be prescribed by local authorities to alter the time scale of local time.

[[term-calendar-day-of-week]]
===== calendar day of week

a day amongst the sequence of week days, namely, Monday, Tuesday, Wednesday, Thursday, Friday, Sat-urday and Sunday

NOTE: The calendar day of week is represented by a single digit ordinal number identifying a calendar day within a week, from [1] (identifying Monday) through [7] (identifying Sunday)

[[term-calendar-day-of-month]]
===== calendar day of month

the ordinal number of a calendar day within a calendar month (X.X.X)

NOTE: The calendar day of month is represented by a two-digit  ordinal number identifying the calendar day within a calendar month from [01] identifying the first calendar day of a calendar month) through [28], [29], [30], or [31] (depending on the month) identifying the last day of the month.

[[term-calendar-day-of-year]]
===== calendar day of year

the ordinal number of a calendar day (X.X.X) within a _calendar year_ (<<term-calendar-year>>)

NOTE: The calendar day of year is represented by a three-digit  ordinal number identifying the calendar day within a calendar year, from [001] (identifying January 1) through [365] (common year) or [366] (leap year) identifying January 31

[[term-week]]
===== week

_duration_ (<<term-duration>>) of a _calendar week_ (<<term-calendar-week>>)

NOTE: The term "`week`" applies also to the duration of any time interval which starts at a certain time of day at a certain calendar day and ends at the same time of day at the same calendar day of the next calendar week.

[[term-calendar-week]]
===== calendar week

any seven calendar day interval within a single _calendar year_ (<<term-calendar-year>>) which begins on Monday and ends on Sunday, according to the rule that the first calendar week of a year is that one which includes the first Thursday of that year and that the last calendar week of a calendar year is the week immediately preceding the first calendar week of the next calendar year

NOTE: a calendar week within a year is identified by a two-digit ordinal number from [01] for the first calendar week through [52] or [53] (depending on the number of calendar weeks in that calendar year)

[[term-month]]
===== month

_duration_ (<<term-duration>>) of a _calendar month_ (<<term-calendar-month>>)

NOTE: The term "`month`" applies also to the duration of any time interval which starts at a certain time of day at a certain calendar day of the calendar month and ends at the same time of day at the same calendar day of the next calendar month, if it exists.

NOTE: In certain applications a month is considered as a duration of 30 calendar days.

[[term-calendar-month]]
===== calendar month

_time interval_ <<term-time-interval>> resulting from a defined division of a _calendar year_ (<<term-calendar-year>>), each containing a specific number of _calendar days_ (<<term-calendar-day>>)

NOTE: In the Gregorian calendar, each calendar month within its calendar year is identified by a specific name, and represented by a two-digit  ordinal number from [01] for January to [12] for December.

NOTE: See 4.2.1 for the names of the months of the calendar year in the _Gregorian calendar_ (<<term-gregorian-calendar>>), listed in their order of occurrence, for their number of days, and for the ordinal dates of the days in common and leap years.

NOTE: A calendar month is in common parlance often referred to as month, however in this document calendar month and month have different definitions.

[[term-year]]
===== year

duration (X.X.X.X) of a _calendar year_ (<<term-calendar-year>>)

NOTE: In the Gregorian calendar, a year has 365 or 366 days. The duration is 366 days if the corresponding time interval begins February 28 or earlier in a leap year or March 2 or later in a year immediately preceding a leap year.  If the interval begins February 29 (on a leap year), or March 1 of a year preceding a leap year, the end date has to be agreed on. Otherwise the duration is 365 days.

NOTE: The term "`year`" applies also to the duration of any time interval which starts at a certain time of day at a certain calendar date of the calendar year and ends at the same time of day at the same calendar date of the next calendar year with the exception noted in note 1.

[[term-calendar-year]]
===== calendar year

_time interval_ <<term-time-interval>> defined by the calendar (X.X.X) system

NOTE: The Gregorian calendar defines a calendar year to be either 365 or 366 days, which begins on January 1 and ends on December 31, each Gregorian calendar year can be identified by a 4 digit ordinal number beginning with [0000] for year zero, through [9999].

NOTE: The number of digits may exceed 4 in the case of expanded representation.

NOTE: The year number may be preceded by a minus sign to indicate a year preceding year zero.

[[term-decade]]
===== decade

_time interval_ <<term-time-interval>> unit of 10 _calendar years_ (<<term-calendar-year>>),  beginning with a year whose year number is divisible without remainder by ten , in the _Gregorian calendar_ (<<term-gregorian-calendar>>)

NOTE: decade is also used to refer to an arbitrary  duration of 10 years, however decade  is not used as such in this document.

[[term-century]]
===== century

_time interval_ <<term-time-interval>> of 100 _calendar years_ (<<term-calendar-year>>) duration, beginning with a _centennial year_ (<<term-centennial-year>>), in the _Gregorian calendar_ (<<term-gregorian-calendar>>)

NOTE: Century is also used to refer to an arbitrary duration of 100 years, however century  is not used as such in this document.

[example]
The 19th century covers the years 1800 through 1899, however in common parlance, it is sometimes considered to cover the years 1801 through 1900.

==== Representations and formats

[[term-dt-expression]]
===== date and time expression

expression indicating a _time_ <<term-time>>, _time interval_ <<term-time-interval>> or _recurring time interval_ <<term-recurring-time-interval>>

[example]
'2018-08-01' is a date and time expression that indicates the first day of August of 2018 in the Gregorian calendar.

[[term-dt-representation]]
===== date and time representation

expression describing the format of one or more _date and time expressions_ (<<term-dt-expression>>)

[example]
[date] is a date and time representation that can be expanded as [year][month][day], which itself can be expanded into [YYYY][MM][DD]; '20180801' is a date and time expression that conforms to this representation.

[[term-time-scale-component]]
===== time scale component

representation of a _time scale unit_ (<<term-time-scale-unit>>) within a _date and time expression_ (<<term-dt-expression>>) or a date and time representation (<<term-dt-representation>>)

NOTE: A time scale component is considered of a higher order if the time scale unit it represents has a strictly larger time interval than that of another, which is considered to be a lower order component.

NOTE: Common usage of this term often omits the leading phrase "`time scale`", such as representing a "`time scale component calendar year`" by just "`calendar year component`". This usage is deemed accepted in this document.

[example]
calendar year, calendar month, calendar day, hour, minutes, seconds are time scale components of a complete representation.

[[term-basic-format]]
===== basic format

_date and time representation_ (<<term-dt-representation>>) that does not include separators between its _time scale components_ (<<term-time-scale-component>>)

[[term-extended-format]]
===== extended format

extension of the _basic format_ (<<term-basic-format>>) that includes separators between its _time scale components_ (<<term-time-scale-component>>)

[[term-complete-representation]]
===== complete representation

_date and time representation_ (<<term-dt-representation>>) that includes all the _time scale components_ (<<term-time-scale-component>>) associated with the expression

[[term-representation-with-reduced-precision]]
===== representation with reduced precision

abbreviation of a _date and time representation_ (<<term-dt-representation>>) by omission of lower order _time scale components_ (<<term-time-scale-component>>)

[[term-decimal-representation]]
===== decimal representation

expansion of a _date and time representation_ (<<term-dt-representation>>) by addition of a decimal fraction to the lowest order _time scale component_ (<<term-time-scale-component>>) of the expression

[[term-expanded-representation]]
===== expanded representation

expansion of a _date and time representation_ (<<term-dt-representation>>) to allow identification of _calendar dates_ (<<term-calendar-date>>) in _calendar years_ (<<term-calendar-year>>) outside the range [0000] till [9999]



=== Abbreviations

BIPM:: Bureau International des Poids et Mesures / The International Bureau of Weights and Measures
CIPM:: Comité International des Poids et Mesures / The International Committee of Weights and Measures
TAI:: International Atomic Time
UTC::	Coordinated Universal Time
SI:: International System of Units

