// FROM 8601-1


[[terms-units]]
==== Time and date units

[[term-second]]
===== second

base unit of _duration_ (<<term-duration>>) measurement in the International System of Units (SI)

NOTE: As defined by the CGPM (Conférence générale des poids et mesures, General Conference on Weights and Measures) on the proposal of the CIPM (Comité International des Poids et Mesures, International Committee of Weights and Measures).

//NOTE: See also <<ISO80000-3,clause 3-7.a>>.
NOTE: See also <<ISO80000-3>>.


[[term-clock-second]]
===== clock second

_time scale unit_ (<<term-time-scale-unit>>) whose _duration_ (<<term-duration>>) is one _second_ (<<term-second>>)

NOTE: Clock second is in common parlance often referred to as second, however in this document clock second and second have different definitions.

[[term-minute]]
===== minute

_duration_ (<<term-duration>>) of 60 _seconds_ (<<term-second>>)

//NOTE: See also <<ISO80000-3,clause 3-7.b>>.
NOTE: See also <<ISO80000-3>>.

NOTE: The duration of a minute is 60 seconds except if modified by the insertion or deletion of a leap second


[[term-clock-minute]]
===== clock minute

_time scale unit_ (<<term-time-scale-unit>>) whose duration is one _minute_ (<<term-minute>>)

NOTE: Clock minute is in common parlance often referred to as minute, however in this document clock minute and minute have different definitions.

[[term-hour]]
===== hour

_duration_ (<<term-duration>>) of 60 _minutes_ (<<term-minute>>)

//NOTE: See also <<ISO80000-3,clause 3-7.c>>.
NOTE: See also <<ISO80000-3>>.

[[term-clock-hour]]
===== clock hour

_time scale unit_ (<<term-time-scale-unit>>) whose _duration_ (<<term-duration>>) is  one _hour_ (<<term-hour>>)

NOTE: Clock hour is in common parlance often referred to as hour, however in this document clock hour and hour have different definitions.


[[term-calendar-date]]
===== calendar date

particular _calendar day_ (<<term-calendar-day>>) represented by its _calendar year_ (<<term-calendar-year>>), its _calendar month_ (<<term-calendar-month>>) and its _calendar day of month_ (<<term-calendar-day-of-month>>)


[[term-ordinal-date]]
===== ordinal date

particular _calendar day_ (<<term-calendar-day>>) represented by its _calendar year_ (<<term-calendar-year>>) and its _calendar day of year_ (<<term-calendar-day-of-year>>)


[[term-week-date]]
===== week date

particular _calendar day_ (<<term-calendar-day>>) represented by its _calendar year_ (<<term-calendar-year>>)
to which its _calendar week_ (<<term-calendar-week>>) belongs, its _calendar week of year_ (<<term-calendar-week-of-year>>), and its _calendar day of week_ (<<term-calendar-day-of-week>>)


[[term-day]]
===== day

_duration_ (<<term-duration>>) of a _calendar day_ (<<term-calendar-day>>)

NOTE: The term "`day`" applies also to the duration of any _time interval_ (<<term-time-interval>>) which starts at a certain _time of day_ (<<term-time-of-day>>) on a certain calendar day and ends at the same time of day on the next calendar day.

//NOTE: See also <<ISO80000-3,clause 3-7.d>>.
NOTE: See also <<ISO80000-3>>.

[[term-calendar-day]]
===== calendar day

_time scale unit_ (<<term-time-scale-unit>>) starting at the beginning of the day and ending with the beginning of the next day [the latter being the starting _instant_ (<<term-instant>>) of the next calendar day]

NOTE: Calendar day is in common parlance often referred to as day, however in this document calendar day and day have different definitions.

[NOTE]
====
The _duration_ (<<term-duration>>) of a calendar day using the _24-hour clock_ (<<term-24-hour-clock>>) is 24 _hours_ (<<term-hour>>); except if modified by:

* the insertion or deletion of _leap seconds_ (<<term-leap-second>>), by decision of the IERS; or
* the insertion or deletion of other time intervals, as may be prescribed by local authorities to alter the _time scale_ (<<term-time-scale>>) of local time.
====

[[term-calendar-day-of-week]]
===== calendar day of week

day amongst the sequence of _week calendar_ (<<term-week-calendar>>) days,
namely, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday or Sunday

NOTE: The week calendar is defined in <<week-calendar>>.

[[term-calendar-day-of-month]]
===== calendar day of month

ordinal number of a _calendar day_ (<<term-calendar-day>>) within a _calendar month_ (<<term-calendar-month>>)


[[term-calendar-day-of-year]]
===== calendar day of year

ordinal number of a _calendar day_ (<<term-calendar-day>>) within a _calendar year_ (<<term-calendar-year>>)


[[term-week]]
===== week

_duration_ (<<term-duration>>) of a _calendar week_ (<<term-calendar-week>>)

NOTE: The term "`week`" applies also to the duration of any _time interval_ (<<term-time-interval>>) which starts at a certain _time of day_ (<<term-time-of-day>>) at a certain _calendar day of week_ (<<term-calendar-day-of-week>>) and ends at the same time of day at the same calendar day of week in the next calendar week.

[[term-calendar-week]]
===== calendar week

_time scale unit_ (<<term-time-scale-unit>>) of seven _calendar days_ (<<term-calendar-day>>) within a single _calendar year_ (<<term-calendar-year>>) which begins on Monday and ends on Sunday,
according to the _week calendar_ (<<term-week-calendar>>)


[[term-calendar-week-of-year]]
===== calendar week of year

ordinal number of a _calendar week_ (<<term-calendar-week>>) within a _calendar year_ (<<term-calendar-year>>) of the _week calendar_ (<<term-week-calendar>>)


[[term-month]]
===== month

_duration_ (<<term-duration>>) of a _calendar month_ (<<term-calendar-month>>)

NOTE: The term "`month`" applies also to the duration of any _time interval_ (<<term-time-interval>>) which starts at a certain _time of day_ (<<term-time-of-day>>) at a certain _calendar day_ (<<term-calendar-day>>) of the calendar month and ends at the same time of day at the same calendar day of the next calendar month, if it exists.

NOTE: In certain applications a month is considered as a duration of 30 calendar days, but such usage is not supported by this document.

[[term-calendar-month]]
===== calendar month

_time scale unit_ (<<term-time-scale-unit>>) resulting from a defined division of a _calendar year_ (<<term-calendar-year>>), each containing a specific number of _calendar days_ (<<term-calendar-day>>)

NOTE: A calendar month is in common parlance often referred to as month, however in this document calendar month and month have different definitions.

[[term-year]]
===== year

_duration_ (<<term-duration>>) of a _calendar year_ (<<term-calendar-year>>)

NOTE: In the _Gregorian calendar_ (<<term-gregorian-calendar>>), a year has 365 or 366 _days_ (<<term-day>>). The duration is 366 days if the corresponding _time interval_ (<<term-time-interval>>) begins February 28 or earlier in a _leap year_ (<<term-leap-year>>) or March 2 or later in a year immediately preceding a leap year. If the interval begins February 29 (on a leap year), or March 1 of a year preceding a leap year, the end date has to be agreed on. Otherwise the duration is 365 days.

NOTE: The term "`year`" applies also to the duration of any _time interval_ (<<term-time-interval>>) which starts at a certain _time of day_ (<<term-time-of-day>>) at a certain _calendar date_ (<<term-calendar-date>>) of the calendar year and ends at the same time of day at the same calendar date of the next calendar year with the exception noted in Note 1 to entry.

//NOTE: Also see <<ISO80000-3,annex C.3-7>>.

[[term-calendar-year]]
===== calendar year

_time scale unit_ (<<term-time-scale-unit>>) defined by the _calendar_ (<<term-calendar>>) system

[[term-decade]]
===== decade

_time scale unit_ (<<term-time-scale-unit>>) of 10 _calendar years_ (<<term-calendar-year>>), beginning with a year whose year number is divisible without remainder by ten

NOTE: Decade is also used to refer to an arbitrary _duration_ (<<term-duration>>) of 10 years, however decade is not used as such in this document.

[[term-century]]
===== century

_time scale unit_ (<<term-time-scale-unit>>) of 100 _calendar years_ (<<term-calendar-year>>) _duration_ (<<term-duration>>), beginning with a year whose year number is divisible without remainder by 100

NOTE: Century is also used to refer to an arbitrary duration of 100 years, however century is not used as such in this document.

[example]
The "`19th century`" covers the years 1800 through 1899 as in common parlance.



// FROM 8601-2

[[term-season]]
===== season

element of a _normal sub-year grouping_ (<<term-normal-sub-year-grouping>>),
amongst which the transition between each element can be based on
calendrical, meteorological, astronomical, solar or ecological events

[[term-four-season-calendar]]
===== four-season calendar

calendar in general use resulting from the division of a calendar year
into four _seasons_ (<<term-season>>)

NOTE: A single calendar date may represent different seasons
depending on local customs or location, such as the difference
between the northern or southern hemispheres.

NOTE: The four seasons are namely _spring_ (<<term-spring>>),
_summer_ (<<term-summer>>), _autumn_ (<<term-autumn>>), and
_winter_ (<<term-winter>>)

[[term-spring]]
===== spring
_season_ (<<term-season>>) in the _four-season calendar_ (<<term-four-season-calendar>>)
following _winter_ (<<term-winter>>) and preceding _summer_ (<<term-summer>>)

[[term-summer]]
===== summer
_season_ (<<term-season>>) in the _four-season calendar_ (<<term-four-season-calendar>>)
following _spring_ (<<term-spring>>) and preceding _autumn_ (<<term-autumn>>)

[[term-autumn]]
===== autumn
_season_ (<<term-season>>) in the _four-season calendar_ (<<term-four-season-calendar>>)
following _summer_ (<<term-summer>>) and preceding _winter_ (<<term-winter>>)

[[term-winter]]
===== winter
_season_ (<<term-season>>) in the _four-season calendar_ (<<term-four-season-calendar>>)
 following _autumn_ (<<term-autumn>>) and preceding _spring_ (<<term-spring>>)


