
[[terms-representations]]
==== Representations and formats

[[term-dt-expression]]
===== date and time expression

expression indicating a _time_ <<term-time>>, _time interval_ (<<term-time-interval>>) or _recurring time interval_ <<term-recurring-time-interval>>

[example]
'2018-08-01' is a date and time expression that indicates the first day of August of 2018 in the _Gregorian calendar_ (<<term-gregorian-calendar>>).


[[term-dt-representation]]
===== date and time representation

representation of the format of one or more _date and time expressions_ (<<term-dt-expression>>)

[example]
[date] is a date and time representation that can be expanded as [year][month][day], which itself can be expanded into [YYYY][MM][DD]; '20180801' is a date and time expression that conforms to this representation.


[[term-time-scale-component]]
===== time scale component

representation of a _time scale unit_ (<<term-time-scale-unit>>) within a _date and time expression_ (<<term-dt-expression>>) or a _representation_ (<<term-dt-representation>>)

NOTE: A time scale component is considered of a higher order of another, if the time scale unit it represents has a strictly larger time interval than that of that another; the latter time scale component is therefore considered to be of a lower order.

NOTE: Common usage of this term often omits the leading phrase "`time scale`", such as representing a "`time scale component calendar year`" by just "`calendar year component`". This usage is deemed accepted in this document.

[example]
Calendar year, calendar month, calendar day, clock hour, clock minute, clock second are time scale components of a complete representation.

[example]
The calendar year time scale component is considered of a higher order than the calendar month time scale component, which is in turn of a higher order than the calendar day time scale component.


[[term-repeat-rule]]
===== repeat rule

consists of a set of _eligible time intervals_ (<<term-eligible-time-interval>>) and _selection rules_ (<<term-selection-rule>>) that allows computation of a set of _matching instants_ (<<term-matching-instant>>)

[[term-selection-rule]]
===== selection rule
rule specifying restrictions on the value of a _time scale component_ (<<iso8601-1,clause 3.1.3.9>>)

===== repeat cycle
set of _repeating instants_ (<<iso8601-1,clause 3.1.1.2>>), calculated by a specified start instant and specified _duration_ (<<iso8601-1,clause 3.1.1.6>>) gap between the repeating instants

[[term-eligible-time-interval]]
===== eligible time interval
_time interval_ (<<iso8601-1,clause 3.1.1.3>>) eligible for matching using _selection rules_ (<<term-selection-rule>>)

[[term-matching-instant]]
===== matching instants
set of _instants_ (<<iso8601-1,clause 3.1.1.2>>), computed by a _repeating rule_ (<<term-repeat-rule>>), that belongs within _eligible time intervals_ (<<term-eligible-time-interval>>) and fulfils criteria set by specified _selection rules_ (<<term-selection-rule>>)

